name: Generate Submission Zip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semi-submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Server Autograde Test
        run: |
          cd server
          pip3 install ftplib pyftpdlib
          output=$(python3 autograde_server.py)
          echo $output
          if echo "$output" | grep -q "Your credit is 28"; then
            echo "Server Autograde Test Passed!"
          else
            echo "Server Autograde Test Failed!"
            exit 1
          fi
          cd ..

      - name: Client Autograde Test
        run: |
          cd client
          cd test
          output=$(python3 autograde_client.py)
          echo $output
          if echo "$output" | grep -q "Your client credit is 22"; then
            echo "Client Autograde Test Passed!"
          else
            echo "Client Autograde Test Failed!"
            exit 1
          fi
          cd ..
          cd ..

      - name: Install Pandoc and Texlive
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-lang-chinese

      - name: Set DOC_PATH and SUBMIT_FOLDER
        run: |
          echo "DOC_PATH=doc" >> $GITHUB_ENV
          mkdir -p studentID
          echo "SUBMIT_FOLDER=studentID" >> $GITHUB_ENV

      - name: Generate Udp answer PDF
        run: |
          cd ${DOC_PATH}
          pandoc udpAnswer.md --template=template.latex -o udpAnswer.pdf --pdf-engine=xelatex
          cd ..

      - name: Generate whole project report PDF
        run: |
          cd ${DOC_PATH}
          pandoc report.md --template=template.latex -o report.pdf --pdf-engine=xelatex
          cd ..
          cp ${DOC_PATH}/report.pdf ${SUBMIT_FOLDER}

      - name: Copy Udp answers
        run: |
          mkdir -p ${SUBMIT_FOLDER}/udp/src
          mkdir -p ${SUBMIT_FOLDER}/udp/doc
          cp $(pwd)/udp/c/client.c ${SUBMIT_FOLDER}/udp/src
          cp $(pwd)/udp/c/server.c ${SUBMIT_FOLDER}/udp/src
          cp $(pwd)/udp/c/Makefile ${SUBMIT_FOLDER}/udp/src
          cp ${DOC_PATH}/udpAnswer.pdf ${SUBMIT_FOLDER}/udp/doc

      - name: Copy Server Source Code
        run: |
          mkdir -p ${SUBMIT_FOLDER}/server/include
          mkdir -p ${SUBMIT_FOLDER}/server/src
          cp $(pwd)/server/include/* -r ${SUBMIT_FOLDER}/server/include
          cp $(pwd)/server/src/* -r ${SUBMIT_FOLDER}/server/src
          cp $(pwd)/server/autograde_server.py ${SUBMIT_FOLDER}/server
          cp $(pwd)/server/Makefile ${SUBMIT_FOLDER}/server

      - name: Copy Client Source Code
        run: |
          mkdir -p ${SUBMIT_FOLDER}/client/src/include
          mkdir -p ${SUBMIT_FOLDER}/client/src/src
          mkdir -p ${SUBMIT_FOLDER}/client/src/test
          cp $(pwd)/client/include/* -r ${SUBMIT_FOLDER}/client/src/include
          cp $(pwd)/client/src/* -r ${SUBMIT_FOLDER}/client/src/src
          cp $(pwd)/client/test/* -r ${SUBMIT_FOLDER}/client/src/test
          cp $(pwd)/client/CMakeLists.txt ${SUBMIT_FOLDER}/client/src
          touch ${SUBMIT_FOLDER}/PLACE_DEMO_MP4_HERE
          touch ${SUBMIT_FOLDER}/client/PLACE_CLIENT_EXE_HERE

      - name: Generate Submission
        uses: actions/upload-artifact@v3
        with:
          name: semi-submission
          path: studentID
